version: '3.8'

services:

  sm-frontend-dev:
    build:
      context: .
      target: dev
    container_name: sm-frontend-dev
    network_mode: sm-network
    env_file:
      - ${env_file:-.env}
    ports:
      - "${FRONTEND_DEV_PORT}:${FRONTEND_PORT}"


  sm-frontend-stage:
    build:
      context: .
      target: prod
    # image: ${GITLAB_URL}/${IMAGE_NAME:-sm-frontend}:${TAG:-latest}
    container_name: sm-frontend-stage
    network_mode: sm-network
    env_file:
      - ${env_file:-.env}
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 

  sm-frontend-prod:
    image: ${IMAGE_NAME:-sm-frontend}
    container_name: sm-frontend-prod
    network_mode: sm-network
    env_file:
      - ${env_file:-.env}
    ports: 
      - "${FRONTEND_PROD_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 


networks:
  sm-network:
    external: true 


  
      
