version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - ${env_file:-.env}
    networks:
      - sm-network
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - /srv/mongo-data-social-media:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    env_file:
      - ${env_file:-.env}
    ports:
      - "${MONGO_EXPRESS_PORT}:8085"
    networks:
      - sm-network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}

    depends_on:
      - mongodb


  sm-backend-dev:
    build:
      context: .
      target: dev
    container_name: sm-back-dev
    networks:
      - sm-network
    env_file:
      - ${env_file:-.env}
    depends_on:
      - mongodb
      - mongo-express
    ports:
      - "${BACKEND_DEV_PORT}:${BACKEND_PORT}"


  sm-backend-stage:
    build:
      context: .
      target: prod
    image: ${GITLAB_URL}/${IMAGE_NAME:-sm-backend}:${TAG:-latest}
    container_name: sm-back-stage
    env_file:
      - ${env_file:-.env}
    networks:
      - sm-network
    depends_on:
      - mongodb
      - mongo-express
    ports:
      - "${BACKEND_PROD_PORT}:${BACKEND_PORT}"


  sm-backend-prod:
    image: ${IMAGE_NAME:-sm-backend}
    container_name: sm-back-prod
    env_file:
      - ${env_file:-.env}
    networks:
      - sm-network
    depends_on:
      - mongodb
      - mongo-express
    ports:
      - "${BACKEND_PROD_PORT}:${BACKEND_PORT}" 


networks:
  sm-network:
      name: sm-network 

